p8105_hw2_yd2739
================
Yuxuan Du
2023-09-26

## Problem 1

We’ll use the data in `pols-month.csv`, `unemployment.csv`, and
`snp.csv`

**load `pols-month.csv`**

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
pols_month_df = 
  read_csv("HW2_P1_DATA/pols-month.csv")|>
  janitor::clean_names()|>
  separate(
    col = mon,
    into = c("year", "month", "day"), 
    sep = "-") |>
  mutate(
    month = case_match(
      month, 
      '01' ~ "January", 
      '02' ~ "February", 
      '03' ~ "March", 
      '04' ~ "April", 
      '05' ~ "May", 
      '06' ~ "June", 
      '07' ~ "July", 
      '08' ~ "August", 
      '09' ~ "September", 
      '10' ~ "October", 
      '11' ~ "November", 
      '12' ~ "December"
    )
  )|>
  mutate(
    president = case_match(
      prez_gop, 
      2 ~ "republican",
      1 ~ "republican", 
      0 ~ "democratic"
    )
  )|>
  subset(select = -c(prez_gop, prez_dem, day))
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pols_month_df
```

    ## # A tibble: 822 × 9
    ##    year  month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president 
    ##    <chr> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     
    ##  1 1947  January        23      51     253      23      45     198 democratic
    ##  2 1947  February       23      51     253      23      45     198 democratic
    ##  3 1947  March          23      51     253      23      45     198 democratic
    ##  4 1947  April          23      51     253      23      45     198 democratic
    ##  5 1947  May            23      51     253      23      45     198 democratic
    ##  6 1947  June           23      51     253      23      45     198 democratic
    ##  7 1947  July           23      51     253      23      45     198 democratic
    ##  8 1947  August         23      51     253      23      45     198 democratic
    ##  9 1947  September      23      51     253      23      45     198 democratic
    ## 10 1947  October        23      51     253      23      45     198 democratic
    ## # ℹ 812 more rows

**load `snp.csv`**

``` r
snp_df = 
  read_csv("HW2_P1_DATA/snp.csv")|>
  janitor::clean_names()|>
  separate(
    col = date,
    into = c("month", "day", "year"), 
    sep = "/") |>
  mutate(
    month = case_match(
      month, 
      '1' ~ "January", 
      '2' ~ "February", 
      '3' ~ "March", 
      '4' ~ "April", 
      '5' ~ "May", 
      '6' ~ "June", 
      '7' ~ "July", 
      '8' ~ "August", 
      '9' ~ "September", 
      '10' ~ "October", 
      '11' ~ "November", 
      '12' ~ "December"
    )
  )|>
  mutate(
    year = as.numeric(year)
  )|>
  mutate(
    year = ifelse(year>=50, 1900+year, 2000+year), 
    year = as.character(year)
  )|>
  relocate(c(year, month))
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp_df
```

    ## # A tibble: 787 × 4
    ##    year  month    day   close
    ##    <chr> <chr>    <chr> <dbl>
    ##  1 2015  July     1     2080.
    ##  2 2015  June     1     2063.
    ##  3 2015  May      1     2107.
    ##  4 2015  April    1     2086.
    ##  5 2015  March    2     2068.
    ##  6 2015  February 2     2104.
    ##  7 2015  January  2     1995.
    ##  8 2014  December 1     2059.
    ##  9 2014  November 3     2068.
    ## 10 2014  October  1     2018.
    ## # ℹ 777 more rows

**load`unemployment.csv`**

``` r
unemployment_df = 
  read_csv("HW2_P1_DATA/unemployment.csv")|>
  janitor::clean_names()|>
  pivot_longer(
    jan:dec, 
    names_to = "month",
    values_to = "unemployment", 
  )|>
  mutate(
    year = as.character(year)
  )|>
  mutate(
    month = case_match(
      month, 
      'jan' ~ "January", 
      'feb' ~ "February", 
      'mar' ~ "March", 
      'apr' ~ "April", 
      'may' ~ "May", 
      'jun' ~ "June", 
      'jul' ~ "July", 
      'aug' ~ "August", 
      'sep' ~ "September", 
      'oct' ~ "October", 
      'nov' ~ "November", 
      'dec' ~ "December"
    )
  )
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment_df
```

    ## # A tibble: 816 × 3
    ##    year  month     unemployment
    ##    <chr> <chr>            <dbl>
    ##  1 1948  January            3.4
    ##  2 1948  February           3.8
    ##  3 1948  March              4  
    ##  4 1948  April              3.9
    ##  5 1948  May                3.5
    ##  6 1948  June               3.6
    ##  7 1948  July               3.6
    ##  8 1948  August             3.9
    ##  9 1948  September          3.8
    ## 10 1948  October            3.7
    ## # ℹ 806 more rows

**merge three dataframe**

``` r
P1_whole_df = 
  left_join(pols_month_df, snp_df, by = c("year", "month"))|>
  left_join(unemployment_df, by = c("year", "month"))
P1_whole_df
```

    ## # A tibble: 822 × 12
    ##    year  month   gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president day  
    ##    <chr> <chr>     <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <chr>
    ##  1 1947  January      23      51     253      23      45     198 democrat… <NA> 
    ##  2 1947  Februa…      23      51     253      23      45     198 democrat… <NA> 
    ##  3 1947  March        23      51     253      23      45     198 democrat… <NA> 
    ##  4 1947  April        23      51     253      23      45     198 democrat… <NA> 
    ##  5 1947  May          23      51     253      23      45     198 democrat… <NA> 
    ##  6 1947  June         23      51     253      23      45     198 democrat… <NA> 
    ##  7 1947  July         23      51     253      23      45     198 democrat… <NA> 
    ##  8 1947  August       23      51     253      23      45     198 democrat… <NA> 
    ##  9 1947  Septem…      23      51     253      23      45     198 democrat… <NA> 
    ## 10 1947  October      23      51     253      23      45     198 democrat… <NA> 
    ## # ℹ 812 more rows
    ## # ℹ 2 more variables: close <dbl>, unemployment <dbl>

So the pols_month dataset contains the information of president,
governors, senators, and representatives from republican and democratic
during different period of time.

The snp dataset contains the Standard & Poor’s stock market index during
different period of time.

The unemployment dataset contains the unemployment rate in the US during
different period of time.

The time span of the dataset is from 1947 to 2015. The size of the
merged dataset is 822 x 12.

## Problem 2

``` r
# load the dataset, change the format of date, recalculate homes_powered
mr_trash_wheel_df = 
  readxl::read_excel("HW2_P2_DATA/202207 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N549")|>
  janitor::clean_names()|>
  mutate(
    date = substr(date, nchar(date) - 1, nchar(date))
  )|>
  mutate(
    homes_powered = (weight_tons*500/30)
  )|>
  mutate(name = "Mr_trash_wheel")
mr_trash_wheel_df
```

    ## # A tibble: 547 × 15
    ##    dumpster month year  date  weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <chr> <chr> <chr>       <dbl>              <dbl>           <dbl>
    ##  1        1 May   2014  16           4.31                 18            1450
    ##  2        2 May   2014  16           2.74                 13            1120
    ##  3        3 May   2014  16           3.45                 15            2450
    ##  4        4 May   2014  17           3.1                  15            2380
    ##  5        5 May   2014  17           4.06                 18             980
    ##  6        6 May   2014  20           2.71                 13            1430
    ##  7        7 May   2014  21           1.91                  8             910
    ##  8        8 May   2014  28           3.7                  16            3580
    ##  9        9 June  2014  05           2.52                 14            2400
    ## 10       10 June  2014  11           3.76                 18            1340
    ## # ℹ 537 more rows
    ## # ℹ 8 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <dbl>, homes_powered <dbl>, name <chr>

``` r
professor_trash_wheel_df = 
  readxl::read_excel("HW2_P2_DATA/202207 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", range = "A2:M96")|>
  janitor::clean_names()|>
  mutate(
    date = substr(date, nchar(date) - 1, nchar(date))
  )|>
  mutate(
    homes_powered = (weight_tons*500/30), 
    year = as.character(year)
  )|>
  mutate(name = "Professor_trash_wheel")
professor_trash_wheel_df
```

    ## # A tibble: 94 × 14
    ##    dumpster month    year  date  weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <chr>    <chr> <chr>       <dbl>              <dbl>           <dbl>
    ##  1        1 January  2017  02           1.79                 15            1950
    ##  2        2 January  2017  30           1.58                 15            9540
    ##  3        3 February 2017  26           2.32                 18            8350
    ##  4        4 February 2017  26           3.72                 15            8590
    ##  5        5 February 2017  28           1.45                 15            7830
    ##  6        6 March    2017  30           1.71                 15            8210
    ##  7        7 April    2017  01           1.82                 15            9830
    ##  8        8 April    2017  20           2.37                 15            9240
    ##  9        9 May      2017  10           2.64                 15            9540
    ## 10       10 May      2017  26           2.78                 15            8230
    ## # ℹ 84 more rows
    ## # ℹ 7 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   homes_powered <dbl>, name <chr>

``` r
gwynnda_trash_wheel_df = 
  readxl::read_excel("HW2_P2_DATA/202207 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel", range = "A2:K108")|>
  janitor::clean_names()|>
  mutate(
    date = substr(date, nchar(date) - 1, nchar(date))
  )|>
  mutate(
    homes_powered = (weight_tons*500/30),
    year = as.character(year)
  )|>
  mutate(name = "Gwynnda_trash_wheel")

trash_wheel_collection_df = 
  bind_rows(mr_trash_wheel_df, professor_trash_wheel_df, gwynnda_trash_wheel_df)

total_weight_professor = sum(pull(professor_trash_wheel_df, weight_tons))

total_cigarette_butts_gwynnda_july_2021 = subset(
  gwynnda_trash_wheel_df, 
  month == "July" & year == "2021"
  )|>
  pull(
    cigarette_butts
    )|>
  sum()
gwynnda_trash_wheel_df
```

    ## # A tibble: 106 × 12
    ##    dumpster month  year  date  weight_tons volume_cubic_yards plastic_bottles
    ##       <dbl> <chr>  <chr> <chr>       <dbl>              <dbl>           <dbl>
    ##  1        1 July   2021  03           0.93                 15            1200
    ##  2        2 July   2021  07           2.26                 15            2000
    ##  3        3 July   2021  07           1.62                 15            1800
    ##  4        4 July   2021  16           1.76                 15            1000
    ##  5        5 July   2021  30           1.53                 15            2100
    ##  6        6 August 2021  11           2.06                 15            2400
    ##  7        7 August 2021  14           1.9                  15            2700
    ##  8        8 August 2021  16           2.16                 15            3000
    ##  9        9 August 2021  16           2.6                  15             980
    ## 10       10 August 2021  17           3.21                 15             240
    ## # ℹ 96 more rows
    ## # ℹ 5 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   plastic_bags <dbl>, homes_powered <dbl>, name <chr>

The size of the merged dataframe is 747 x 14.

Some interesting information: Only Mr.Trash Wheel has the variable of
`sports_ball`;

Gwynnda Trash Wheel does not have the variable `galss_bottles`;

The category in Gwynnda dataset contains a category of `plastic_bags`,
but it does not include category `grocery_bags` and `chip_bags` that
exist in other two dataset. This might be an inconsistency in variable
names, but I didn’t change the format.

The way of recording date is kind of redundant since there are variables
for year and month (the format of date is changed later)

There might be missing data in the dataset gwynnda_trash_wheel_df since
there are days they collected tons of trash while all trash category
counts is 0.

The total weight of trash collected by Professor Trash Wheel is 190.12.

The total number of cigarette butts collected by Gwynnda in July of 2021
is 1.63^{4}.

## Problem 3

``` r
demo_info_df = 
  read_csv("HW2_P3_DATA/MCI_baseline.csv", skip = 1)|>
  janitor::clean_names()|>
  mutate(
    sex = recode(sex, "1" = "male", "0" = "female"),
    apoe4 = recode(apoe4, "1" = "carrier", "0" = "non-carrier"), 
    sex = factor(sex), 
    apoe4 = factor(apoe4)
  )|>
  subset(
    current_age < age_at_onset | age_at_onset == "."
  )|>
  rename(
    age_starting = current_age
  )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(demo_info_df)
```

    ## # A tibble: 6 × 6
    ##      id age_starting sex    education apoe4       age_at_onset
    ##   <dbl>        <dbl> <fct>      <dbl> <fct>       <chr>       
    ## 1     1         63.1 female        16 carrier     .           
    ## 2     2         65.6 female        20 carrier     .           
    ## 3     3         62.5 male          16 carrier     66.8        
    ## 4     4         69.8 female        16 non-carrier .           
    ## 5     5         66   male          16 non-carrier 68.7        
    ## 6     6         62.5 male          16 non-carrier .

``` r
avg_age_baseline = mean(pull(demo_info_df, age_starting))

total_women = subset(
  demo_info_df, 
  sex == 0
  )|>
  nrow()

total_women_carrier = subset(
  demo_info_df, 
  sex == 0 & apoe4 == 1
  )|>
  nrow()

women_apoe4_percent = total_women_carrier/total_women
```

We can seee that there are 479 people met the requirement and joined the
experiment, 93 of the 479 developed MCI at last. The average baseline
age is 65.0286013. The proportion of women in the study who are APOE4
carriers is NaN.

``` r
amyloid_df = 
  read_csv("HW2_P3_DATA/mci_amyloid.csv", skip = 1)|>
  janitor::clean_names()|>
  rename(
    id=study_id, 
    ratio_base_line = baseline, 
    ratio_second_year = time_2, 
    ratio_fourth_year = time_4, 
    ratio_sixth_year = time_6, 
    ratio_eighth_year = time_8)
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(amyloid_df)
```

    ## # A tibble: 6 × 6
    ##      id ratio_base_line ratio_second_year ratio_fourth_year ratio_sixth_year
    ##   <dbl> <chr>           <chr>             <chr>             <chr>           
    ## 1     1 0.1105487       <NA>              0.109325197       0.104756131     
    ## 2     2 0.107481183     0.109157373       0.109457839       0.105729713     
    ## 3     3 0.106087034     0.108744509       0.106065035       <NA>            
    ## 4     4 0.109251358     0.108699686       0.110540386       0.107476797     
    ## 5     5 0.107950408     0.112273883       0.115139677       0.106606054     
    ## 6     6 0.112426974     0.112853415       0.11143945        0.110279277     
    ## # ℹ 1 more variable: ratio_eighth_year <chr>

We also need to skip the first line of mci_amyloid.csv since it is not
the header for dataframe. Also to follow the format of `demo_info_df`,
the variable `study_id` is renamed as `id`. There are missing values in
dataset, but it might means they didn’t show up at that time. The size
of the dataframe is 487 x 6.

``` r
only_baseline = demo_info_df |>
  anti_join(amyloid_df, by = "id")
head(only_baseline)
```

    ## # A tibble: 6 × 6
    ##      id age_starting sex    education apoe4       age_at_onset
    ##   <dbl>        <dbl> <fct>      <dbl> <fct>       <chr>       
    ## 1    14         58.4 female        20 non-carrier 66.2        
    ## 2    49         64.7 male          16 non-carrier 68.4        
    ## 3    92         68.6 female        20 non-carrier .           
    ## 4   179         68.1 male          16 non-carrier .           
    ## 5   268         61.4 female        18 carrier     67.5        
    ## 6   304         63.8 female        16 non-carrier .

``` r
only_amyloid = amyloid_df |>
  anti_join(demo_info_df, by = "id")
head(only_amyloid)
```

    ## # A tibble: 6 × 6
    ##      id ratio_base_line ratio_second_year ratio_fourth_year ratio_sixth_year
    ##   <dbl> <chr>           <chr>             <chr>             <chr>           
    ## 1    72 0.106965463     <NA>              0.107266218       0.106665207     
    ## 2   234 0.110521689     0.110988335       0.110318671       0.107334344     
    ## 3   283 0.113436336     0.106568976       0.11338643        0.10820706      
    ## 4   380 0.111158847     0.104560429       0.106822683       0.104961175     
    ## 5   484 0.11139422      0.110936838       0.109182887       0.110607585     
    ## 6   485 0.106042813     0.105158363       0.107758828       0.107281321     
    ## # ℹ 1 more variable: ratio_eighth_year <chr>

``` r
both_df = merge(demo_info_df, amyloid_df)
head(both_df)
```

    ##   id age_starting    sex education       apoe4 age_at_onset ratio_base_line
    ## 1  1         63.1 female        16     carrier            .       0.1105487
    ## 2  2         65.6 female        20     carrier            .     0.107481183
    ## 3  3         62.5   male        16     carrier         66.8     0.106087034
    ## 4  4         69.8 female        16 non-carrier            .     0.109251358
    ## 5  5         66.0   male        16 non-carrier         68.7     0.107950408
    ## 6  6         62.5   male        16 non-carrier            .     0.112426974
    ##   ratio_second_year ratio_fourth_year ratio_sixth_year ratio_eighth_year
    ## 1              <NA>       0.109325197      0.104756131       0.107257697
    ## 2       0.109157373       0.109457839      0.105729713        0.10661845
    ## 3       0.108744509       0.106065035             <NA>       0.106152357
    ## 4       0.108699686       0.110540386      0.107476797       0.111212209
    ## 5       0.112273883       0.115139677      0.106606054       0.106052066
    ## 6       0.112853415        0.11143945      0.110279277       0.114982747

``` r
write.csv(both_df, "HW2_P3_DATA/merged.csv", row.names = FALSE)
```

There are 16 participants appear only in the myloid dataset and 8
participants appear only in the baseline dataset.

For the merged dataset, there are 471 observation, each with 11
variables.
